### ISSUE TITLE
The latest version can not be used.

### ISSUE THREAD

**Issue by findlayfeng** [NordicSemiconductor/pc-nrfutil#123]
[root@84754c687206 /]# nrfutil
Traceback (most recent call last):
  File "/usr/sbin/nrfutil", line 11, in <module>
    load_entry_point('nrfutil==3.4.0', 'console_scripts', 'nrfutil')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/nordicsemi/__main__.py", line 49, in <module>
    from nordicsemi.dfu.bl_dfu_sett import BLDFUSettings
  File "/usr/lib/python3.6/site-packages/nordicsemi/dfu/bl_dfu_sett.py", line 50, in <module>
    from nordicsemi.dfu import intelhex
  File "/usr/lib/python3.6/site-packages/nordicsemi/dfu/intelhex/__init__.py", line 322
    print "IntelHex.tobinarray: 'pad' parameter is deprecated."
                                                              ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by findlayfeng** [comment]
Sorry I used python3
