### ISSUE TITLE
Release v6.0.0a1 crashes on Windows

### ISSUE THREAD

**Issue by cypress-speedycat** [NordicSemiconductor/pc-nrfutil#278]
```
[7472] Failed to execute script __main__
Traceback (most recent call last):
  File "nordicsemi\__main__.py", line 1458, in <module>
  File "site-packages\click\core.py", line 764, in __call__
  File "site-packages\click\core.py", line 717, in main
  File "site-packages\click\core.py", line 1137, in invoke
  File "site-packages\click\core.py", line 1137, in invoke
  File "site-packages\click\core.py", line 956, in invoke
  File "site-packages\click\core.py", line 555, in invoke
  File "nordicsemi\__main__.py", line 863, in generate
  File "nordicsemi\dfu\package.py", line 413, in generate_package
  File "nordicsemi\dfu\package.py", line 614, in normalize_firmware_to_bin
  File "nordicsemi\dfu\nrfhex.py", line 181, in tobinfile
  File "nordicsemi\dfu\nrfhex.py", line 135, in minaddr
TypeError: '>' not supported between instances of 'NoneType' and 'int'

```

It was downloaded from your [Releases page](https://github.com/NordicSemiconductor/pc-nrfutil/releases)

**Comment by cypress-speedycat** [comment]
A bit more info here. 

It's on a Windows 7 machine.

Generating keys works. The crash comes from when trying to generate a ZIP file, like `nrfutil pkg generate --debug-mode --application app.hex --key-file key.pem app_dfu_package.zip`. 

This also happens with the 5.2.0 release version.

I've tried running the `nrfutil` command in _Msys2_, _Git bash_ and _Windows Powershell_.

`pip install nrfutil` doesn't even compile with python3 on _Msys2_.

**Comment by MaartenArits** [comment]
The pip package is still python 2.7, adafruit-nrfutil is python 3.5. Should pip be updated? It is not consistent with the readme.

**Comment by bihanssen** [comment]
@cypress-speedycat, are seeing the issue also after release of nrfutil v6 final?

**Comment by bihanssen** [comment]
Closing due to inactivity.
