### ISSUE TITLE
nrfutil crashes if private key file is not found

### ISSUE THREAD

**Issue by Raane** [NordicSemiconductor/pc-nrfutil#34]
nrfutil crashes if the private key file is not found. The error from python is readable enough to understand what happened, but a single line like "File not found: private.pem" would be better.

Copy-paste from console when triggering the error:

```
$ nrfutil keys display --key pk --format code --out_file dfu_public_key.c private.pem

Traceback (most recent call last):
  File "C:\Python27\Scripts\nrfutil-script.py", line 9, in <module>
    load_entry_point('nrfutil==1.4.16', 'console_scripts', 'nrfutil')()
  File "C:\Python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "C:\Python27\lib\site-packages\nordicsemi\__main__.py", line 264, in display
    raise NordicSemiException("File not found: %s" % key_file)
pc_ble_driver_py.exceptions.NordicSemiException: File not found: private.pem
```

**Comment by carlescufi** [comment]
In general nrfutil displays Python backtraces when an error happens. This is not an oversight but rather something that we have decided to keep this way for now.
