### ISSUE TITLE
DFU Server logging fails due to piccata type mismatch

### ISSUE THREAD

**Issue by nealjack** [NordicSemiconductor/pc-nrfutil#346]
I am using the most recent versions of pc-nrfutil and piccata for a remote DFU server for some nRF52840 devices using nordic's DFU over CoAP. There seems to be a type mismatch between the expected 'tuple' and 'named tuple' returned by piccata's [tsocket transport](https://github.com/NordicSemiconductor/piccata/blob/master/transport/tsocket.py#L31). I have a [pr that will fix this issue in piccata](https://github.com/NordicSemiconductor/piccata/pull/5), however that has been unanswered for a couple years. Maybe it needs to be fixed on the pc-nrfutil end?

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/nealsjackson/.local/lib/python3.8/site-packages/transport/tsocket.py", line 49, in run
    self._receive_callback(data, addr, own_addr)
  File "/home/nealsjackson/.local/lib/python3.8/site-packages/transport/base.py", line 71, in _receive
    rcvr.receive(data, remote, local)
  File "/home/nealsjackson/.local/lib/python3.8/site-packages/piccata/core.py", line 530, in receive
    self._message_layer.receive(data, remote, local)
  File "/home/nealsjackson/.local/lib/python3.8/site-packages/piccata/core.py", line 195, in receive
    self._transaction_layer.receive_message(message, remote, local)
  File "/home/nealsjackson/.local/lib/python3.8/site-packages/piccata/core.py", line 415, in receive_message
    self._process_request(message)
  File "/home/nealsjackson/.local/lib/python3.8/site-packages/piccata/core.py", line 317, in _process_request
    response = self._request_handler.receive_request(request)
  File "/home/nealsjackson/.local/lib/python3.8/site-packages/nordicsemi/thread/dfu_server.py", line 380, in receive_request
    return handler(request)
  File "/home/nealsjackson/.local/lib/python3.8/site-packages/nordicsemi/thread/dfu_server.py", line 215, in _handle_init_request
    logger.debug("Added {} to clients".format(request.remote.addr))
AttributeError: 'tuple' object has no attribute 'addr'
```

**Comment by kenr** [comment]
Hi! We do not have capacity to maintain and release new versions of this utility.
We have made a new utility with the same name and feature set. It can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util
