### ISSUE TITLE
nrfutil fails to run with python3

### ISSUE THREAD

**Issue by Terstegge** [NordicSemiconductor/pc-nrfutil#350]
I just tried to install nrfutil using
pip3 install nrfutil,
but after running the tools I get an error message:
Traceback (most recent call last):
  File "/home/andreas/.local/bin/nrfutil", line 5, in <module>
    from nordicsemi.__main__ import cli
  File "/home/andreas/.local/lib/python3.8/site-packages/nordicsemi/__main__.py", line 49, in <module>
    from nordicsemi.dfu.bl_dfu_sett import BLDFUSettings
  File "/home/andreas/.local/lib/python3.8/site-packages/nordicsemi/dfu/bl_dfu_sett.py", line 51, in <module>
    from nordicsemi.dfu.package import Package
  File "/home/andreas/.local/lib/python3.8/site-packages/nordicsemi/dfu/package.py", line 53, in <module>
    from nordicsemi.dfu.init_packet_pb import InitPacketPB, DFUType, CommandTypes, ValidationTypes, SigningTypes, HashTypes
  File "/home/andreas/.local/lib/python3.8/site-packages/nordicsemi/dfu/init_packet_pb.py", line 38, in <module>
    from . import dfu_cc_pb2 as pb
  File "/home/andreas/.local/lib/python3.8/site-packages/nordicsemi/dfu/dfu_cc_pb2.py", line 18, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

Installation was successfull, though...

**Comment by kenr** [comment]
Hi! We do not have capacity to maintain and release new versions of this utility.
We have made a new utility with the same name and feature set. It can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util
