### ISSUE TITLE
xrange not in python3 any more

### ISSUE THREAD

**Issue by hecko** [NordicSemiconductor/pc-nrfutil#354]
Im running this on python3 installed from brew and nrfjprog version: 10.12.2, JLinkARM.dll version: 6.88a

```
marcel@192 nrf52811-s112-xxx % nrfutil settings generate --family NRF52810 --application ./pca10056e/s112/ses/Output/Release/Exe/ble_app_uart_pca10056e_s112.hex --application-version 1 --bootloader-version 1 --bl-settings-version 2 bootloader_setting.hex

Note: Generating a DFU settings page with backup page included.
This is only required for bootloaders from nRF5 SDK 15.1 and newer.
If you want to skip backup page generation, use --no-backup option.
Traceback (most recent call last):
  File "/usr/local/bin/nrfutil", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nordicsemi/__main__.py", line 389, in generate
    sett.generate(arch=family, app_file=application, app_ver=application_version_internal, bl_ver=bootloader_version,
  File "/usr/local/lib/python3.9/site-packages/nordicsemi/dfu/bl_dfu_sett.py", line 203, in generate
    self.app_bin = Package.normalize_firmware_to_bin(self.temp_dir, app_file)
  File "/usr/local/lib/python3.9/site-packages/nordicsemi/dfu/package.py", line 605, in normalize_firmware_to_bin
    temp = nRFHex(firmware_path)
  File "/usr/local/lib/python3.9/site-packages/nordicsemi/dfu/nrfhex.py", line 77, in __init__
    self.loadfile(source, self.file_format)
  File "/usr/local/lib/python3.9/site-packages/nordicsemi/dfu/intelhex/__init__.py", line 243, in loadfile
    self.loadhex(fobj)
  File "/usr/local/lib/python3.9/site-packages/nordicsemi/dfu/intelhex/__init__.py", line 206, in loadhex
    decode(s, line)
  File "/usr/local/lib/python3.9/site-packages/nordicsemi/dfu/intelhex/__init__.py", line 137, in _decode_record
    for i in xrange(4, 4+record_length):
NameError: name 'xrange' is not defined
```

```
marcel@192 nrf52811-s112-ttc % head `which nrfutil`
#!/usr/local/opt/python@3.9/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys
from nordicsemi.__main__ import cli
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
```

**Comment by hecko** [comment]
My bad!
Requires: Python >=3.6, <3.9
so python 3.9 actually installs nrfutil-5.2.0
