### ISSUE TITLE
`AttributeError` when upgrading firmware via DFU Serial

### ISSUE THREAD

**Issue by gudnimg** [NordicSemiconductor/pc-nrfutil#393]
Steps to reproduce:

* Connect a BLE dongle to USB port in Windows
* Make the BLE dongle enter DFU mode
* Enter command in terminal: `nrfutil dfu serial --package package.zip`

```
C:\nox_git\fwarmx-c1-dongle\projects\fwarmx_c1_dongle>nrfutil dfu serial --package FWARMX_C1_DONGLE_FW_SDAPP.zip
Traceback (most recent call last):
  File "C:\Users\gudnimar\AppData\Local\Programs\Python\Python39\Scripts\nrfutil-script.py", line 33, in <module>
    sys.exit(load_entry_point('nrfutil==6.1.7', 'console_scripts', 'nrfutil')())
  File "C:\Users\gudnimar\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\gudnimar\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\gudnimar\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\gudnimar\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\gudnimar\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\gudnimar\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\gudnimar\AppData\Local\Programs\Python\Python39\lib\site-packages\nordicsemi\__main__.py", line 1073, in serial
    do_serial(package, port, connect_delay, flow_control, packet_receipt_notification, baud_rate, serial_number, True,
  File "C:\Users\gudnimar\AppData\Local\Programs\Python\Python39\lib\site-packages\nordicsemi\__main__.py", line 968, in do_serial
    device = device_lister.get_device(serial_number=serial_number)
  File "C:\Users\gudnimar\AppData\Local\Programs\Python\Python39\lib\site-packages\nordicsemi\lister\device_lister.py", line 67, in get_device
    if "serial_number" in kwargs and (kwargs["serial_number"].lower().lstrip('0') !=
AttributeError: 'NoneType' object has no attribute 'lower'
```

In my case the Serial number is  `None` for a little while, but soon it is not None. Problem here is the code is not checking if the serial number is `None`.

**Comment by kenr** [comment]
We do do not have capacity to maintain and release new versions of this utility.
The utility can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util
